### ISSUE TITLE
Set custom UserAgent on `go-vinyldns` client

### ISSUE THREAD

**Issue by mdb** [vinyldns/terraform-provider-vinyldns#59]
As a maintainer of `terraform-provider-vinyldns`, I'd like `terraform-provider-vinyldns` send a custom `User-Agent` on requests such that usage can be tracked in aggregated logs and operational visibility metrics. I'm imagining a `UserAgent` string such as `terraform-provider-vinyldns/<version>`.

**Comment by marekfilip** [comment]
Hi! I'd like to help, but I don't have an idea where I can get the `version` from, can you give me a clue?

**Comment by mdb** [comment]
@marekfilip Hi there and thanks for the offer to help! Currently, the version is stored in the `GNUMakefile` [here](https://github.com/vinyldns/terraform-provider-vinyldns/blob/master/GNUmakefile#L6) and used [here at build time](https://github.com/vinyldns/terraform-provider-vinyldns/blob/master/GNUmakefile#L40) as well as in [generating terraform-provider-vinyldns GitHub releases](https://github.com/vinyldns/terraform-provider-vinyldns/blob/master/GNUmakefile#L67).

Does that clarify?

**Comment by marekfilip** [comment]
@mdb Great! To make sure is my plan good. I will pass version from main to vinyldns package, if version would be empty I set `UserAgent` as 'terraform-provider-vinyldns` without a version otherwise it will be like `terraform-provider-vinyldns/<version>`. In this way version will be set on build time and released application will introduce herself always with the proper `UserAgent`.
Is that make sense?

**Comment by mdb** [comment]
@marekfilip Yep; if I understand correctly, I think that sounds perfect!

**Comment by marekfilip** [comment]
I'll deal with it on Saturday :v:

**Comment by marekfilip** [comment]
Well, it not saturday but here it is. Sorry for delay.
Thanks in advance for review and information what to change/improve.

**Comment by mdb** [comment]
Thanks @marekfilip !
