### ISSUE TITLE
Vinyldns fails to read record set when trying to fetch via Jenkins after converting from denis to vinyldns resource.

### ISSUE THREAD

**Issue by janani2019** [vinyldns/terraform-provider-vinyldns#93]
I tried to convert the denis resource to vinyldns resource in terraform since the newer version of terraform is not compatible with older vinyldns providers anymore and Jenkins has been throwing this error since then. The same works when i run locally without jenkins with the same credentials. Im using terraform-provider-vinyldns_v0.9.5 and terraform aws provider v2.68. Tried with various vinyl dns proveider versions from terraform-provider-vinyldns_v0.9.1 through terraform-provider-vinyldns_v0.9.5, its the same error.

Error: error reading recordset (xx-xx-xx-xx): Get https://api.vinyldns.comcast.net:9443/zones/xx-xx-xx-xx/recordsets/xx-xx-xx-xx: Forbidden

Anyone faced this ?

**Comment by pauljamescleary** [comment]
Pinging @mdb on this one as he is a little more familiar with the terraform provider

@janani2019 Thanks for opening the issue.  I am not sure if the TF provider spits out the details of the error.  A normal `Forbidden` is an access permissions issues.  For example, user does not have access to the zone, user does not have access to the record set.  From a *read* perspective, I think those are the only conditions for a `Forbidden`.

We have argued that, since DNS is "world readable", that anyone should be able to _read_ any record in the system.  Those restrictions are easy to roll back, but I forget over time where we landed.  Curious if others have thoughts as well.

**Comment by janani2019** [comment]
@pauljamescleary thanks for responding! the same works locally with the same credentials. Im facing `Forbidden` error only when i run via jenkins.

**Comment by pauljamescleary** [comment]
Are you certain that the zone id and record set info is the same?  I reviewed the code today. A forbidden is explicitly an access control issue. I have seen some issues in the past with a 401 error due to request signing issues, but by your comments it appears to be a Forbidden. 

This is definitely the same vinyl database?  We have seen instances where the vinyldns database was different.  We have on a few occasions hit the wrong environment when testing. 

I’ve made a few assumptions as well. My assumption is that you have a vinyldns installation that you are accessing locally as well as via Jenkins.

**Comment by janani2019** [comment]
It was apparently an issue with the proxy from our end. The issue is fixed now.
